### ISSUE TITLE
Crear un método en QuestionAnswer que compruebe si una respuesta es la correcta

### ISSUE THREAD

**Issue by mikelsanvi** [Programacion-DAM/EscapeRoom#1]
Devolverá true si la respuesta proporcionada es igual que la correcta ignorando mayúsuclas y minúsculas

Hacer tests
- Que sea diferente
- Que sea igual
- Que sea igual con diferentes mayúsculas/minúsculas

**Comment by CarMB** [comment]
Tarea acabada
