### ISSUE TITLE
Un método que permita responder a la pregunta actual

### ISSUE THREAD

**Issue by mikelsanvi** [Programacion-DAM/EscapeRoom#3]
Devolverá true si se ha acertado y false en caso contrario.
Si se acierte se pasará a la siguiente pregunta

Test
- Se ha acertado. Debe devolver true y se debe pasar a la siguiente
- Se ha fallado la pregunta. Debe devolver false y no se debe pasar a la siguiente

**Comment by CarMB** [comment]
tarea hecha
