### ISSUE TITLE
Crear una clase ConsoleEscapeRoom

### ISSUE THREAD

**Issue by mikelsanvi** [Programacion-DAM/EscapeRoom#5]
Una clase que dado un objeto EscapeRoom utilice el Scanner y la salida del log4j para implementar la dínamica del juega:
- Mostrar mensaje de bienvenida
- Mostrar nombre del usuario
- Un bucle de preguntas en las que el usuario meterá las respuestas
- Mostrar un mensaje de felicitación

Crear un ConsoleMain que crea la partida con datos hardcodeados y ejecutamos el juego

**Comment by migsamu** [comment]
Completado!
