### ISSUE TITLE
Cuando se acierta la última pregunta se produce una excepción, hay que arreglar el bug

### ISSUE THREAD

**Issue by mikelsanvi** [Programacion-DAM/EscapeRoom#7]
Esto se debe a que no se está usando el método escapeRoom.isFinished()
![image](https://user-images.githubusercontent.com/281207/112718968-95210400-8ef6-11eb-810e-7b5f50eae1db.png)

**Comment by migsamu** [comment]
Solucionado, para ello ademas de usar el metodo escapeRoom.isFinished() he tenido que modificar otro metodo correctAnswer(String answer) y añadir otra condicion en el if() para que no aumentase el contador y se saliese del indice.
