### ISSUE TITLE
Metodo numLettersPerWordInAnswer

### ISSUE THREAD

**Issue by mikelsanvi** [Programacion-DAM/EscapeRoom#8]
Cread un método en QuestionAnswer que devuelva un array de enteros. El array tendrá tantas posiciones como palabras haya en la respuesta. Cada posición contendrá un entero que se corresponda con el número de letras de la palabra en esa posición.

Por ejemplo:
Respuesta: K2 array: [ 2 ]
Respuesta: Malala Yousafzai array: [ 6,  9]

Haced tests

**Comment by migsamu** [comment]
Hecho junto con Carlos, hemos hecho solo dos test, uno para respuestas de una sola palabra y otro para respuestas de varias palabras. No se nos ocurrian mas tests por si se nos ha escapado algo mas a probar
