### ISSUE TITLE
El juego no es ejecutable

### ISSUE THREAD

**Issue by mikelsanvi** [Programacion-DAM/EscapeRoom#9]
El Main debe instanciar ConsoleEscapeRoom, pasarle la configuración de la partida e invocar el método consoleEscapeRoom.run()

**Comment by migsamu** [comment]
Ya está el main como debería y se puede ejecutar. Ahora ha salido un bug que se acaba el juego en la penúltima pregunta, he intentado solucionarlo pero no he dado con el error, no tenia mucho tiempo lo volveré a mirar.
